In [2]:
import os
import random
import numpy as np
import pandas as pd
import torch
import math
from matplotlib import pyplot as plt
from imageio import imread
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from utils import config

In [14]:
X = np.array([[[[5,8],[0,3]],[[6,5],[7,9]],[[1,1],[2,3]]],[[[4,7],[9,1]],[[8,9],[4,3]],[[7,7],[8,8]]],[[[2,7],[2,9]],[[8,1],[0,6]],[[7,6],[8,6]]]], dtype=float)

In [15]:
for i in range(X.shape[0]): #which image
            for j in range(X.shape[3]): #which channel
                channel_sum = 0
                for k in range(X.shape[1]): #height
                    for l in range(X.shape[2]): #width
                        channel_sum += X[i,k,l,j]
                channel_avg = channel_sum / (X.shape[1] * X.shape[2])
                channel_squares = 0
                for k in range(X.shape[1]): #height
                    for l in range(X.shape[2]): #width
                        channel_squares += (X[i,k,l,j] - channel_avg)**2
                        X[i,k,l,j] -= channel_avg
                channel_stdev = math.sqrt(channel_squares/(X.shape[1] * X.shape[2] - 1))
                for k in range(X.shape[1]): #height
                    for l in range(X.shape[2]): #width
                        X[i,k,l,j] /= channel_stdev
for i in range(X.shape[0]): #which image
            for j in range(X.shape[3]): #which channel
                channel_sum = 0
                for k in range(X.shape[1]): #height
                    for l in range(X.shape[2]): #width
                        channel_sum += X[i,k,l,j]
                channel_avg = channel_sum / (X.shape[1] * X.shape[2])
                channel_squares = 0
                for k in range(X.shape[1]): #height
                    for l in range(X.shape[2]): #width
                        channel_squares += (X[i,k,l,j] - channel_avg)**2
                channel_stdev = math.sqrt(channel_squares/(X.shape[1] * X.shape[2] - 1))
                print(channel_stdev)


1.0
1.0
1.0
0.9999999999999999
1.0
1.0


[[[[ 0  0]
   [-1  0]]

  [[ 0  0]
   [ 1  1]]

  [[ 0  0]
   [ 0  0]]]


 [[[ 0  0]
   [ 0 -1]]

  [[ 0  0]
   [ 0  0]]

  [[ 0  0]
   [ 0  0]]]


 [[[ 0  0]
   [ 0  1]]

  [[ 0 -1]
   [-1  0]]

  [[ 0  0]
   [ 0  0]]]]


In [16]:
a = np.array([[1,2],[3,4]])
b = a
print(b)

[[1 2]
 [3 4]]


In [17]:
a = np.array([1])

In [18]:
print(a)

[1]


In [19]:
a = [2,3,4]

In [20]:
print(a)

[2, 3, 4]


In [21]:
a = [2,3,4]

In [22]:
print(a)

[2, 3, 4]


In [2]:
import numpy as np
b = np.empty((2))

In [3]:
b[0]=1
b[1]=2
print(b)

[1. 2.]


In [5]:
np.append(b,2)

array([1., 2., 2.])

In [6]:
print(b)

[1. 2.]


In [7]:
b = np.append(b,3)
print(b)

[1. 2. 3.]


In [17]:
c=np.empty((5,1))

[ 1.    2.75  6.   10.75 17.    2.  ]


In [19]:
d=[]

In [20]:
d=np.append(d,2)

In [21]:
print(d)

[2.]
